// Document to identify allowed and disallowed CSS properties. Refer to: https://archiveofourown.org/help/skins_creating

// These do not have to be exact matches so they are just in an array
export const ALLOWED_PREFIXES = [
  'background',
  'border',
  'column',
  'cue',
  'flex',
  'font', // font shorthand handled separately
  'layer-background',
  'layout-grid',
  'list-style',
  'margin',
  'marker',
  'outline',
  'overflow',
  'padding',
  'page-break',
  'pause',
  'scrollbar',
  'text',
  'transform',
  'transition',
]

// These are in a set because they must be exact matches
export const ALLOWED_PROPERTIES = new Set([
  '-replace',
  '-use-link-source',
  'accelerator',
  'accent-color',
  'align-content',
  'align-items',
  'align-self',
  'alignment-adjust',
  'alignment-baseline',
  'appearance',
  'azimuth',
  'baseline-shift',
  'behavior',
  'binding',
  'bookmark-label',
  'bookmark-level',
  'bookmark-target',
  'bottom',
  'box-align',
  'box-direction',
  'box-flex',
  'box-flex-group',
  'box-lines',
  'box-orient',
  'box-pack',
  'box-shadow',
  'box-sizing',
  'caption-side',
  'clear',
  'clip',
  'color',
  'color-profile',
  'color-scheme',
  'content',
  'counter-increment',
  'counter-reset',
  'crop',
  'cue',
  'cue-after',
  'cue-before',
  'cursor',
  'direction',
  'display',
  'dominant-baseline',
  'drop-initial-after-adjust',
  'drop-initial-after-align',
  'drop-initial-before-adjust',
  'drop-initial-before-align',
  'drop-initial-size',
  'drop-initial-value',
  'elevation',
  'empty-cells',
  'filter',
  'fit',
  'fit-position',
  'float',
  'float-offset',
  'font',
  'font-effect',
  'font-emphasize',
  'font-emphasize-position',
  'font-emphasize-style',
  'font-family',
  'font-size',
  'font-size-adjust',
  'font-smooth',
  'font-stretch',
  'font-style',
  'font-variant',
  'font-weight',
  'grid-columns',
  'grid-rows',
  'hanging-punctuation',
  'height',
  'hyphenate-after',
  'hyphenate-before',
  'hyphenate-character',
  'hyphenate-lines',
  'hyphenate-resource',
  'hyphens',
  'icon',
  'image-orientation',
  'image-resolution',
  'ime-mode',
  'include-source',
  'inline-box-align',
  'justify-content',
  'layout-flow',
  'left',
  'letter-spacing',
  'line-break',
  'line-height',
  'line-stacking',
  'line-stacking-ruby',
  'line-stacking-shift',
  'line-stacking-strategy',
  'mark',
  'mark-after',
  'mark-before',
  'marks',
  'marquee-direction',
  'marquee-play-count',
  'marquee-speed',
  'marquee-style',
  'max-height',
  'max-width',
  'min-height',
  'min-width',
  'move-to',
  'nav-down',
  'nav-index',
  'nav-left',
  'nav-right',
  'nav-up',
  'opacity',
  'order',
  'orphans',
  'page',
  'page-policy',
  'phonemes',
  'pitch',
  'pitch-range',
  'play-during',
  'position',
  'presentation-level',
  'punctuation-trim',
  'quotes',
  'rendering-intent',
  'resize',
  'rest',
  'rest-after',
  'rest-before',
  'richness',
  'right',
  'rotation',
  'rotation-point',
  'ruby-align',
  'ruby-overhang',
  'ruby-position',
  'ruby-span',
  'size',
  'speak',
  'speak-header',
  'speak-numeral',
  'speak-punctuation',
  'speech-rate',
  'stress',
  'string-set',
  'tab-side',
  'table-layout',
  'target',
  'target-name',
  'target-new',
  'target-position',
  'top',
  'unicode-bibi',
  'unicode-bidi',
  'user-select',
  'vertical-align',
  'visibility',
  'voice-balance',
  'voice-duration',
  'voice-family',
  'voice-pitch',
  'voice-pitch-range',
  'voice-rate',
  'voice-stress',
  'voice-volume',
  'volume',
  'white-space',
  'white-space-collapse',
  'widows',
  'width',
  'word-break',
  'word-spacing',
  'word-wrap',
  'writing-mode',
  'z-index',
])

// Handles the font-face conundrum and disallows CSS injection specifically (even though this should be covered)
export const DISALLOWED_AT_RULES = ['@font-face', '@import']

// Numeric values and units
export const ALLOWED_UNITS = ['cm', 'em', 'ex', 'in', 'mm', 'pc', 'pt', 'px', '%']

export const MAX_DECIMAL_PLACES = 2

// Image formats
export const ALLOWED_IMAGE_FORMATS = ['jpg', 'jpeg', 'gif', 'png']

// Special rules regarding AO3's current CSS setup.
export const SPECIAL_RULES = {
  DISALLOW_FONT_SHORTHAND: true,
  STRIP_COMMENTS: true,
  SINGLE_DECLARATION_PER_PROPERTY: true,
  ALLOW_CSS_VARIABLES_SITE_ONLY: true,
  DISALLOW_VAR_FALLBACKS: true,
}
